{
  "name": "react-webapp",
  "version": "1.0.0",
  "description": "",
  "private": true,
  "sideEffects": [
    "*.less"
  ],
  "scripts": {
    "weinre": "weinre --boundHost -all-",
    "build:vendors": "webpack --config=dll/webpack.dll.js",
    "build:dev": "cross-env NODE_ENV=development webpack",
    "build:test": "cross-env NODE_ENV=testing webpack",
    "build:prod": "cross-env NODE_ENV=production webpack -p",
    "cache:clear": "rm -rf node_modules/.cache",
    "server:test": "cross-env NODE_ENV=testing node server.js",
    "server:prod": "cross-env NODE_ENV=production node server.js",
    "start": "cross-env NODE_ENV=development webpack-dev-server --hot",
    "ah:dev": "concurrently -k \"npm start --app=ah\" \"npm run weinre\"",
    "ah:test": "npm run build:test --app=ah && npm run server:test --app=ah",
    "ah:test:docker": "npm run ah:test && npm run cache:clear",
    "ah:prod": "npm run build:prod --app=ah && npm run server:prod --app=ah",
    "ah:prod:docker": "npm run ah:prod && npm run cache:clear",
    "eam:dev": "concurrently -k \"npm start --app=eam\" \"npm run weinre\"",
    "eam:test": "npm run build:test --app=eam && npm run server:test --app=eam",
    "eam:test:docker": "npm run eam:test && npm run cache:clear",
    "eam:prod": "npm run build:prod --app=eam",
    "eam:prod:docker": "npm run eam:prod && npm run cache:clear",
    "osm:dev": "npm start --app=osm",
    "osm:test": "npm run build:test --app=osm && npm run server:test --app=osm",
    "osm:prod": "npm run build:prod --app=osm && npm run server:prod --app=osm",
    "ufms:dev": "npm start --app=ufms",
    "ufms:test": "npm run build:test --app=ufms && npm run server:test --app=ufms",
    "ufms:test:docker": "npm run ufms:test && npm run cache:clear",
    "ufms:prod": "npm run build:prod --app=ufms && npm run server:prod --app=ufms",
    "ufms:prod:docker": "npm run ufms:prod && npm run cache:clear",
    "analyze": "cross-env NODE_ENV=production ANALYZE=analyze npm run eam:prod",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "Cheau",
  "license": "MIT",
  "dependencies": {
    "antd": "^3.13.0",
    "antd-mobile": "^2.2.8",
    "babel-plugin-react-css-modules": "^5.0.0",
    "babel-polyfill": "^6.26.0",
    "bizcharts": "^3.5.3",
    "compression": "^1.7.3",
    "crypto-js": "^3.1.9-1",
    "draft-js": "^0.10.5",
    "es6-promise": "^4.2.5",
    "express": "^4.16.4",
    "fecha": "^3.0.2",
    "history": "^4.7.2",
    "humps": "^2.0.1",
    "if-env": "^1.0.4",
    "lodash": "^4.17.11",
    "mobx": "^4.9.2",
    "mobx-react": "^5.4.3",
    "node-rsa": "^1.0.3",
    "normalizr": "^3.3.0",
    "quagga": "^0.12.1",
    "raf": "^3.4.1",
    "react": "^16.7.0",
    "react-amap": "^1.2.8",
    "react-css-modules": "^4.7.9",
    "react-dom": "^16.7.0",
    "react-icons-kit": "^1.2.1",
    "react-ink": "^6.4.0",
    "react-loadable": "^5.5.0",
    "react-motion": "^0.5.2",
    "react-router": "^4.3.1",
    "react-router-dom": "^4.3.1",
    "react-swipe": "^6.0.4",
    "react-table": "^6.9.0",
    "react-tap-event-plugin": "^3.0.3",
    "react-tap-or-click": "^0.2.1",
    "react-transition-group": "^2.5.3",
    "url-search-params-polyfill": "^5.1.0",
    "victory": "^31.2.0",
    "whatwg-fetch": "^3.0.0"
  },
  "devDependencies": {
    "@babel/core": "^7.2.2",
    "@babel/plugin-proposal-class-properties": "^7.3.0",
    "@babel/plugin-proposal-decorators": "^7.3.0",
    "@babel/plugin-proposal-object-rest-spread": "^7.3.2",
    "@babel/preset-env": "^7.3.1",
    "@babel/preset-react": "^7.0.0",
    "babel-eslint": "^10.0.1",
    "babel-loader": "^8.0.5",
    "babel-plugin-dynamic-import-webpack": "^1.1.0",
    "babel-plugin-import": "^1.11.0",
    "babel-plugin-syntax-dynamic-import": "^6.18.0",
    "babel-plugin-transform-react-constant-elements": "^6.23.0",
    "babel-plugin-transform-react-inline-elements": "^6.22.0",
    "babel-plugin-transform-react-jsx": "^6.24.1",
    "babel-plugin-wildcard": "^5.0.0",
    "babel-runtime": "^6.26.0",
    "bundle-loader": "^0.5.6",
    "compression-webpack-plugin": "^2.0.0",
    "concurrently": "^4.1.0",
    "copy-webpack-plugin": "^4.6.0",
    "cross-env": "^5.2.0",
    "css-loader": "^2.1.0",
    "eslint": "^5.13.0",
    "eslint-config-airbnb": "^17.1.0",
    "eslint-config-airbnb-base": "^13.1.0",
    "eslint-loader": "^2.1.1",
    "eslint-plugin-import": "^2.16.0",
    "eslint-plugin-jsx-a11y": "^6.2.0",
    "eslint-plugin-react": "^7.12.4",
    "exports-loader": "^0.7.0",
    "expose-loader": "^0.7.5",
    "file-loader": "^3.0.1",
    "imports-loader": "^0.8.0",
    "json-loader": "^0.5.7",
    "less": "^3.9.0",
    "less-loader": "^4.1.0",
    "node-sass": "^4.11.0",
    "postcss-each": "^0.10.0",
    "postcss-import": "^12.0.1",
    "postcss-less": "^3.1.2",
    "postcss-mixins": "^6.2.1",
    "postcss-nested": "^4.1.1",
    "react-hot-loader": "^4.6.5",
    "resolve-url-loader": "^3.0.0",
    "sass-loader": "^7.1.0",
    "style-loader": "^0.23.1",
    "url-loader": "^1.1.2",
    "webpack": "^4.29.4",
    "webpack-bundle-analyzer": "^3.0.3",
    "webpack-cli": "^3.2.1",
    "webpack-dev-server": "^3.1.14",
    "weinre": "^2.0.0-pre-I0Z7U9OV"
  }
}